# Generated by Django 6.0 on 2025-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField()),
                ('vehicle_type', models.CharField()),
                ('manufacture', models.CharField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
