# Generated by Django 6.0 on 2025-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
